name: geocoder
description: Forward and reverse geocoding.
version: 0.3.0
homepage: https://github.com/aloisdeniel/flutter_geocoder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aloisdeniel.geocoder
        pluginClass: GeocoderPlugin
      ios:
        pluginClass: GeocoderPlugin
